image: shebgregor/ci-golang

before_script:
  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - 'echo -e "Host gitlab\n\tHostName gitlab.com\n\tIdentityFile ~/.ssh/id_rsa\n\tUser git\n" >> ~/.ssh/config'
  -  git config --global url.ssh://git@gitlab.com/.insteadOf https://gitlab.com/

stages:
  - build
  - delivery
  - deploy

build:
  stage: build
  variables:
    APP_PATH: gitlab.com/swarmfund/psim
  script:
    - mkdir -p $GOPATH/src/$APP_PATH
    - cp -rf ./* $GOPATH/src/$APP_PATH
    - cd $GOPATH/src/$APP_PATH
    - go build -o bin/psim -a gitlab.com/swarmfund/psim/psim/cmd/psim
    - cp -rf ./bin/ /builds/swarmfund/psim/bin/
  artifacts:
      expire_in: 1 week
      paths:
        - bin/psim
  only:
    - staging
    - dev


delivery:
  image: shebgregor/alpine-rsync-git
  stage: delivery
  script:
    - rsync bin/psim ubuntu@$HOST_DEV:artifacts/psim/${CI_COMMIT_SHA:0:8}/
  only:
    - staging
    - dev

test:
  stage: test
  variables:
    APP_PATH: gitlab.com/swarmfund/api
  script:
    - mkdir -p $GOPATH/src/$APP_PATH
    - cp -rf ./* $GOPATH/src/$APP_PATH
    - cd $GOPATH/src/$APP_PATH
    - go test ./...

.deploy: &deploy
  stage: deploy
  script:
    - JOB_NAME=( $CI_JOB_NAME )
    - SERVICE=${JOB_NAME[-1]}
    - BRANCH=${CI_COMMIT_REF_NAME}
    - THOST=$( echo "HOST_${BRANCH}" | awk '{print toupper($0)}' )
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim $BRANCH ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "$SERVICE" http://${!THOST}:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - staging
    - dev

deploy btc_funnel: *deploy
deploy btc_supervisor: *deploy
deploy btc_withdraw: *deploy

deploy eth_funnel: *deploy
deploy eth_supervisor: *deploy
deploy eth_withdraw: *deploy

deploy notifier: *deploy
deploy bearer: *deploy

