image: shebgregor/ci-golang

before_script:
  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)
  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - 'echo -e "Host gitlab\n\tHostName gitlab.com\n\tIdentityFile ~/.ssh/id_rsa\n\tUser git\n" >> ~/.ssh/config'
  -  git config --global url.ssh://git@gitlab.com/.insteadOf https://gitlab.com/

stages:
  - build
  - delivery
  - deploy

build:
  stage: build
  variables:
    APP_PATH: gitlab.com/swarmfund/psim
  script:
    - mkdir -p $GOPATH/src/$APP_PATH
    - cp -rf ./* $GOPATH/src/$APP_PATH
    - cd $GOPATH/src/$APP_PATH
    - go build -o bin/psim -a gitlab.com/swarmfund/psim/psim/cmd/psim
    - cp -rf ./bin/ /builds/swarmfund/psim/bin/
  artifacts:
      expire_in: 1 week
      paths:
        - bin/psim
  only:
    - staging
    - dev


delivery:
  image: shebgregor/alpine-rsync-git
  stage: delivery
  script:
    - rsync bin/psim ubuntu@$HOST_DEV:artifacts/psim/${CI_COMMIT_SHA:0:8}/
  only:
    - staging
    - dev

# ################################# DEPLOY DEV BTC     ################################# #
deploy:dev:btc_funnel:
  stage: deploy
  script:
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim dev ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "btc_funnel" http://$HOST_DEV:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - dev

deploy:dev:btc_supervisor:
  stage: deploy
  script:
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim dev ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "btc_supervisor" http://$HOST_DEV:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - dev

deploy:dev:btc_withdraw:
  stage: deploy
  script:
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim dev ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "btc_withdraw" http://$HOST_DEV:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - dev


# ################################# DEPLOY DEV ETH     ################################# #
deploy:dev:eth_funnel:
  stage: deploy
  script:
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim dev ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "eth_funnel" http://$HOST_DEV:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - dev

deploy:dev:eth_supervisor:
  stage: deploy
  script:
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim dev ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "eth_supervisor" http://$HOST_DEV:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - dev

deploy:dev:eth_withdraw:
  stage: deploy
  script:
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim dev ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "eth_withdraw" http://$HOST_DEV:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - dev

# ################################# DEPLOY STAGING BTC ################################# #
deploy:staging:btc_funnel:
  stage: deploy
  script:
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim staging ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "btc_funnel" http://$HOST_STAGING:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - staging

deploy:staging:btc_supervisor:
  stage: deploy
  script:
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim staging ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "btc_supervisor" http://$HOST_STAGING:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - staging

deploy:staging:btc_withdraw:
  stage: deploy
  script:
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim staging ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "btc_withdraw" http://$HOST_STAGING:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - staging

# ################################# DEPLOY STAGING ETH ################################# #
deploy:staging:eth_funnel:
  stage: deploy
  script:
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim staging ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "eth_funnel" http://$HOST_STAGING:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - staging

deploy:staging:eth_supervisor:
  stage: deploy
  script:
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim staging ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "eth_supervisor" http://$HOST_STAGING:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - staging

deploy:staging:eth_withdraw:
  stage: deploy
  script:
    - ssh ubuntu@$HOST_DEV "artifacts/update.sh psim staging ${CI_COMMIT_SHA:0:8}"
    - 'curl -X POST -H "Content-Type: text/plain" --data "eth_withdraw" http://$HOST_STAGING:8842/931M76zvt1h_sMOFDl_usQ'
  when: manual
  only:
    - staging
