-   repo: https://github.com/dnephin/pre-commit-golang.git
    sha: 823c25f40e37d52765b6469de6df94c08e678784
    hooks:
      -   id: go-fmt
      -   id: go-vet
      -   id: go-lint
      -   id: gometalinter
