# common

log:
  level: debug
  #slack_webhook: "https://hooks.slack.com/services/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"
  #slack_channel: "#reports"
  #slack_level: error
  #formatter: json
  #sentry_dsn: http://...

horizon:
  addr: http://swarm:8000
#  addr: http://localhost:8000

notificator:
  url: http://swarm:9009
  secret: string
  public: string

stripe:
  secret_key: "sk_test_eJjoMw46tfKnJqzxgrMbfPrj"

bitcoin:
  # move node to separate object?
  node_host: swarm
  node_port: 8332
  node_auth_key: dTAwM2IwNGVmOTUwMWJiZjA2YjpwMDA2NWUyN2MxNWY1NTBiOTJh
  testnet: true
  request_timeout_s: 30
  min_deposit_value: 1000000 # 0.01 BTC

ethereum:
  proto: http
  host: swarm
  port: 8545

discovery:
  env: local
  host: localhost
  port: 8500

# services

services:
#  - bearer
  #- notifier
  #- charger
  #- notifier
  #- stripe_supervisor

#  - bitcoin_supervisor
#  - btc_funnel
#  - btc_withdraw
#  - btc_withdraw_verify

  #- eth_supervisor
#  - eth_funnel

  #- stripe_verify
  #- taxman
  #- rate_sync

stripe_supervisor:
  pprof: true
  exchange: GDFI3OE5XRDYZIGPR75V4FNFNVRXP4PBDO6PXXCIG2UJYBUVXHBH2XVR
  signer: SBEVH5NEMWSBUCEUUOOIUPVOAI3NMX2TV6X5IDL7TTKKMAEXESX5UVKK # exchange signer

# BTC
bitcoin_supervisor:
  last_processed_block: 1259180
  # Should actually by 5 (6+ confirmations for transactions)
  last_blocks_not_watch: 0
  supervisor:
    leadership_key: btc_supervisor
    pprof: true
    # Keys should probably differ between stripe and bitcoin
    exchange: G_SOME_VALID_PUBLIC_KEY
    signer: S_SOME_VALID_PRIVATE_KEY

  # TODO Remove after moving logic of the second signature to the verifier.
  additional_signer: S_SOME_VALID_PRIVATE_KEY

btc_funnel:
  hot_address: 2N1w4RzejEWkCyumsZY8prvmRxAPFkcwehb
  cold_address: 2N8hwP1WmJrFF5QWABn38y63uYLhnJYJYTF # testnet faucet
  min_funnel_amount: 0
  max_hot_stock: 15
  dust_output_limit: 0.005

btc_withdraw:
  private_key: cVaoN6CiScaWB8KJCP8cBP3CjEgFfdK6tf3N5gDow499Xr5AZB8N

  hot_wallet_address: 2N1w4RzejEWkCyumsZY8prvmRxAPFkcwehb
  hot_wallet_script_pub_key: a9145f49aacdc4f9a50e71073e8ed3c449a27759517687
  hot_wallet_redeem_script: 522102cff9f17973e0b1d3468ae29532156f43e42d213fa85e1df40154d7f5748fab6221037afc702c97360f5bd534e6e7eeec0963fd71f9e873e31720ba200c131cfc1f1152ae

  min_withdraw_amount: 0.0001

  signer: S_SOME_VALID_PRIVATE_KEY

btc_withdraw_verify:
  host: localhost
  port: 8101

  btc_private_key: cVYHKmhJPJQY8tqW3adCFmePZBd4cdPRanh6yuUEzhzTnvPTsu8t

  hot_wallet_address: 2N1w4RzejEWkCyumsZY8prvmRxAPFkcwehb
  hot_wallet_script_pub_key: a9145f49aacdc4f9a50e71073e8ed3c449a27759517687
  hot_wallet_redeem_script: 522102cff9f17973e0b1d3468ae29532156f43e42d213fa85e1df40154d7f5748fab6221037afc702c97360f5bd534e6e7eeec0963fd71f9e873e31720ba200c131cfc1f1152ae

  min_withdraw_amount: 0.0001

  source: G_SOME_VALID_PUBLIC_KEY
  signer: S_SOME_VALID_PRIVATE_KEY


# ETH
eth_supervisor:
  supervisor:
    leadership_key: eth_supervisor
    exchange: GD7AHJHCDSQI6LVMEJEE2FTNCA2LJQZ4R64GUI3PWANSVEO4GEOWB636
    signer: SBMFQCGDVJBC2NYBRPURK3ISC4XJGGOLHMGHF7MIHVXE2DIQSMY6NYRH

eth_funnel:
  keystore: "/tmp/wallets"

eth_supervisor:
  confirmations: 2
  cursor: 2334122
  base_asset: SUN
  deposit_asset: ETH
  supervisor:
    leadership_key: eth_supervisor
    exchange: GD7AHJHCDSQI6LVMEJEE2FTNCA2LJQZ4R64GUI3PWANSVEO4GEOWB636
    signer: SBMFQCGDVJBC2NYBRPURK3ISC4XJGGOLHMGHF7MIHVXE2DIQSMY6NYRH

forfeit_listener:
  pprof: true
  signer: SBEVH5NEMWSBUCEUUOOIUPVOAI3NMX2TV6X5IDL7TTKKMAEXESX5UVKK
  exchange: SBEVH5NEMWSBUCEUUOOIUPVOAI3NMX2TV6X5IDL7TTKKMAEXESX5UVKK

rate_sync:
  pprof: true
  master: SCIMXOIWIB32R7JI6ISNYSCO2BFST5E6P3TLBM4TTLHH57IK6SJPGZT2
  #signer: SDKYSN7P6Y75ZYWSGKSVSSX6AYTPRQPSUJH5RFITUS7ORZXNR5YYAFXL
  #signer: SAACSTRCVL33FH3K4VT6YDHDUQPCCMFSQGZREH5NUQBE46FWJSALNAB5
  signer: SCIMXOIWIB32R7JI6ISNYSCO2BFST5E6P3TLBM4TTLHH57IK6SJPGZT2
  provider: noor
  noor:
    host: "40.69.204.168"
    port: 8001
    pairs:
      - quote: USD
        code: XAAU
        symbol: "BullionCoin Gold 100 Units"
        weight: 1
      - quote: USD
        code: XAAG
        symbol: "BullionCoin Silver 1 000 Units"
        weight: 50
  assets:
    - quote: USD
      hub: "17"
      ticker: GMGBR1
      code: XAAU
      to_coin: 1
    - quote: USD
      hub: "17"
      ticker: SMGBR5
      code: XAAG
      to_coin: 50

taxman:
  source: GAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHV4
  signer: SCIMXOIWIB32R7JI6ISNYSCO2BFST5E6P3TLBM4TTLHH57IK6SJPGZT2
  # omit these default for production config
  port: 40539
  disable_verify: true

stripe_verify:
  signer: SDGU7S57HA45RWBTDAUR36CH5B6W2SYKFVCDU3IJ6T74S7FCXQVDZII7

charger:
  host: localhost
  port: 7331
  pprof: true

notifier:
  signer: SBMFQCGDVJBC2NYBRPURK3ISC4XJGGOLHMGHF7MIHVXE2DIQSMY6NYRH
  pprof: true
  project_name: "Swarm Fund"

  operations:
    enable: false
    payload_id: 9
    ignore_older_than: 48h
    client_url: http://staging.app.sun.swarm.fund
    cursor: ""

  assets:
    enable: true
    payload_id: 9
    emission_threshold: 1000000 # should be valid: val = amount * 10000 (ONE)
#    check_period: 20s
    check_period: 24h
    notification_receivers:
      - rago@minex-coin.com
    codes:
      - SUN

bearer:
  source: GDHK26UFBGC63UBQCVQLHJD6RAQXLAS7RKJAR5FZQAWMCUBFHRNKFSKC
  signer: SDLZEHWFLOP2BIQBCQIGI7J7BXBAN5S7UESAKYT7XIZC62RG4YLM4FZ7
  abnormal_period: 1m
  sleep_period: 5m
