# common

log:
  level: warn
  env: not-provided # set dev/stage/prod here
  project: not-provided

  #slack_webhook: "https://hooks.slack.com/services/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"
  #slack_channel: "#reports"
  #slack_level: error
  #formatter: json
  #sentry_dsn: http://...

horizon:
  #addr: http://swarm:8000
  addr: http://localhost:8000

notificator:
  url: http://swarm:9009
  secret: string
  public: string

bitcoin:
  # move node to separate object?
  node_host: swarm
  node_port: 8332
  node_auth_key: dTAwM2IwNGVmOTUwMWJiZjA2YjpwMDA2NWUyN2MxNWY1NTBiOTJh
  testnet: true
  request_timeout_s: 30

ethereum:
  proto: http
  host: swarm
  port: 8545

discovery:
  env: local
  host: localhost
  port: 8500

notifications_slack:
  url: https://hooks.slack.com/services/....
  channel_name: "#channel_name"
  icon_emoji: ":mega:"

s3:
  url: http://127.0.0.1:9000
  access_key: 79JUU8NN3K8BPQBD0P2W
  secret_key: N8sE8S5/0XRFVeqIJj2f7UWZYqqo6AClG5BRHCP/
  region: us-west-2
  disable_ssl: true
  s3_force_path_style: true

# services

services:
#  - bearer
#  - notifier
#  - charger

#  - btc_deposit
#  - btc_deposit_verify
#  - eth_supervisor
#   - eth_contracts_deploy

#  - btc_funnel
#  - eth_funnel

#  - btc_withdraw
#  - btc_withdraw_verify
#  - eth_withdraw

#  - taxman
#  - price_setter
#  - price_setter_verify

#  - airdrop_earlybird
#  - airdrop_kyc
#  - airdrop_march_referrals
#  - airdrop_march_20_20

#  - identity_mind
#  - invest_ready

#  - template_provider
#  - wallet_cleaner

bearer:
  source: GDHK26UFBGC63UBQCVQLHJD6RAQXLAS7RKJAR5FZQAWMCUBFHRNKFSKC
  signer: SDLZEHWFLOP2BIQBCQIGI7J7BXBAN5S7UESAKYT7XIZC62RG4YLM4FZ7
  abnormal_period: 1m
  sleep_period: 5m

notifier:
  source: G_SOME_VALID_PUBLIC_KEY
  signer: S_SOME_VALID_PRIVATE_KEY

  order_cancelled:
    cursor: 1

    emails:
      subject: "IO cancelled"

      request_type: 10 # 10 means that email will be sent only once per each unique token
      request_token_suffix: _io_cancelled # Email with same token will be sent only once

      template_name: io-cancelled

      template_link_url: https://invest.swarm.fund

  kyc_created:
    cursor: 1

    emails:
      subject: "KYC request created"

      request_type: 10 # 10 means that email will be sent only once per each unique token
      request_token_suffix: _kyc_request_created # Email with same token will be sent only once

      template_name: kyc-created

      template_link_url: https://invest.swarm.fund

  kyc_approved:
    cursor: 1

    emails:
      subject: "KYC request approved"

      request_type: 10 # 10 means that email will be sent only once per each unique token
      request_token_suffix: _kyc_request_approved # Email with same token will be sent only once

      template_name: kyc-approved

      template_link_url: https://invest.swarm.fund

  kyc_rejected:
    cursor: 1

    emails:
      subject: "KYC request rejected"

      request_type: 10 # 10 means that email will be sent only once per each unique token
      request_token_suffix: _kyc_request_rejected # Email with same token will be sent only once

      template_name: kyc-rejected

      template_link_url: https://invest.swarm.fund

charger:
  host: localhost
  port: 7331
  pprof: true

forfeit_listener:
  pprof: true
  signer: SBEVH5NEMWSBUCEUUOOIUPVOAI3NMX2TV6X5IDL7TTKKMAEXESX5UVKK
  exchange: SBEVH5NEMWSBUCEUUOOIUPVOAI3NMX2TV6X5IDL7TTKKMAEXESX5UVKK

# deposits
btc_deposit:
  last_processed_block: 1260685
  # Should actually by 5 (6+ confirmations for transactions)
  last_blocks_not_watch: 0
  min_deposit_amount: 500000 # satoshis (0.005 BTC)
  deposit_asset: BTC
  fixed_deposit_fee: 100000 # satoshis (0.001 BTC)

  source: G_SOME_VALID_PUBLIC_KEY
  signer: S_SOME_VALID_PRIVATE_KEY

  # TODO Remove after moving logic of the second signature to the verifier.
  additional_signer: S_SOME_VALID_PRIVATE_KEY

btc_deposit_verify:
  host: localhost
  port: 8102

  # Should actually by 5 (6+ confirmations for transactions)
  last_blocks_not_watch: 0
  min_deposit_amount: 500000 # 0.005 BTC (integer in satoshis)
  deposit_asset: BTC
  fixed_deposit_fee: 100000 # 0.001 BTC (integer in satoshis)

  signer: S_SOME_VALID_PRIVATE_KEY

eth_supervisor:
  confirmations: 2
  cursor: 2405320
  base_asset: ETH
  deposit_asset: SUN
  fixed_deposit_fee: 1000000000000000 # 0.001 ETH

  supervisor:
    leadership_key: eth_supervisor
    exchange: G_SOME_VALID_PUBLIC_KEY
    signer: S_SOME_VALID_PRIVATE_KEY

eth_contracts_deploy:
  source: G_SOME_VALID_PUBLIC_KEY
  signer: S_SOME_VALID_PRIVATE_KEY

  eth_private_key: contracts_deployer_private_key_hex
  contract_owner: contract_owner_address_hex
  gas_price: 1000000000 # TODO Add comment

# funnels
btc_funnel:
  extended_private_key: xprv...
  keys_to_derive: 10000 # number of key to derive from extended private key

  hot_address: 2N1w4RzejEWkCyumsZY8prvmRxAPFkcwehb # hot wallet
  cold_address: 2N8hwP1WmJrFF5QWABn38y63uYLhnJYJYTF # 2N8hwP1WmJrFF5QWABn38y63uYLhnJYJYTF is testnet faucet

  last_processed_block: 1260685
  min_funnel_amount: 0 # (float in BTC)
  max_hot_stock: 50 # (float in BTC)
  dust_output_limit: 0.005 # (float in BTC)
  max_fee_per_kb: 0.00024 # 24000 satoshi (float in BTC)
  blocks_to_be_included: 4 # from 2 to 25

  min_balance_alarm_threshold: 100 # (float in BTC)
  min_balance_alarm_period: 1h

eth_funnel:
  seed: "some_valid_eth_seed"
  destination: "address_of_eth_hot_wallet"
  confirmations: 1
  threshold: 1
  gas_price: 1000000000
  keys_to_derive: 10

#withdrawals
btc_withdraw:
  btc_private_key: cVaoN6CiScaWB8KJCP8cBP3CjEgFfdK6tf3N5gDow499Xr5AZB8N

  hot_wallet_address: 2N1w4RzejEWkCyumsZY8prvmRxAPFkcwehb
  hot_wallet_script_pub_key: a9145f49aacdc4f9a50e71073e8ed3c449a27759517687
  hot_wallet_redeem_script: 522102cff9f17973e0b1d3468ae29532156f43e42d213fa85e1df40154d7f5748fab6221037afc702c97360f5bd534e6e7eeec0963fd71f9e873e31720ba200c131cfc1f1152ae

  min_withdraw_amount: 10000 # 0.0001 BTC (integer in satoshis)

  signer: S_SOME_VALID_PRIVATE_KEY

btc_withdraw_verify:
  host: localhost
  port: 8101

  btc_private_key: cVYHKmhJPJQY8tqW3adCFmePZBd4cdPRanh6yuUEzhzTnvPTsu8t

  hot_wallet_address: 2N1w4RzejEWkCyumsZY8prvmRxAPFkcwehb
  hot_wallet_script_pub_key: a9145f49aacdc4f9a50e71073e8ed3c449a27759517687
  hot_wallet_redeem_script: 522102cff9f17973e0b1d3468ae29532156f43e42d213fa85e1df40154d7f5748fab6221037afc702c97360f5bd534e6e7eeec0963fd71f9e873e31720ba200c131cfc1f1152ae

  min_withdraw_amount: 10000 # 0.0001 BTC (integer in satoshis)

  source: G_SOME_VALID_PUBLIC_KEY
  signer: S_SOME_VALID_PRIVATE_KEY

eth_withdraw:
  key: "hot_wallet_private_key"
  asset: "ETH"
  gas_price: 1000000000
  source: G_SOME_VALID_PUBLIC_KEY
  signer: S_SOME_VALID_PRIVATE_KEY

price_setter:
  base_asset: "ETH"
  quote_asset: "USD"

  submit_period: 15s
  providers:
    - name: "bitfinex"
      period: 15s
    - name: "coinmarketcap"
      period: 15s
    - name: "bitstamp"
      period: 15s
    - name: gdax
      period: 1s # does not apply any changes as we are using sockets
  providers_to_agree: 3
  max_price_delta_percent: "10"
  verifier_service_name: price_setter_verify

  source: GD7AHJHCDSQI6LVMEJEE2FTNCA2LJQZ4R64GUI3PWANSVEO4GEOWB636
  signer: SCIMXOIWIB32R7JI6ISNYSCO2BFST5E6P3TLBM4TTLHH57IK6SJPGZT2

price_setter_verify:
  host: localhost
  port: 8501

  base_asset: "ETH"
  quote_asset: "USD"

  providers:
    - name: "bitfinex"
      period: 15s
    - name: "coinmarketcap"
      period: 15s
    - name: "bitstamp"
      period: 15s
    - name: gdax
      period: 1s # does not apply any changes as we are using sockets
  providers_to_agree: 3
  max_price_delta_percent: "10"

  signer: S
  verifier_service_name: SOME_VERIFIER_SERVICE_NAME

# airdrops
airdrop_earlybird:
  issuance:
    asset: SWM
    amount: 100000000 # 100 SWM (in stroops)

  registered_before: "2018-02-05T14:00:00" # +14 - the latest existing GMT

  source: G_SOME_VALID_PUBLIC_KEY
  signer: S_SOME_VALID_PRIVATE_KEY

  emails:
    subject: "Airdrop"
#    email_subject: "Airdrop delaying"

    request_type: 10 # 10 means that email will be sent only once per each unique token
    request_token_suffix: _airdrop # Email with same token will be sent only once

    template_name: airdrop.html
  #  template_name: airdrop_delaying.html

    template_link_url: https://invest.swarm.fund

  white_list: [
"G_SOME_VALID_ACCOUNT_ADDRESS_1",
"G_SOME_VALID_ACCOUNT_ADDRESS_2"]

airdrop_kyc:
  issuance:
    asset: SWM
    amount: 10000000 # 10 SWM (in stroops)

  source: G_SOME_VALID_PUBLIC_KEY
  signer: S_SOME_VALID_PRIVATE_KEY

  emails:
    subject: "KYC Verification Bonus"

    request_type: 10 # 10 means that email will be sent only once per each unique token
    request_token_suffix: _airdrop_kyc # Email with same token will be sent only once

    template_name: airdrop_kyc.html

    template_link_url: https://invest.swarm.fund

  black_list: [
"G_SOME_VALID_ACCOUNT_ADDRESS_1",
"G_SOME_VALID_ACCOUNT_ADDRESS_2"]

airdrop_march_referrals:
  issuance_asset: SWM
  snapshot_time: "2018-04-22T11:30:00"
  approve_wait_finish_time: "2018-04-25T11:30:00"

  source: G_SOME_VALID_PUBLIC_KEY
  signer: S_SOME_VALID_PRIVATE_KEY

  emails:
    subject: "March Madness Referral Bonus"

    request_type: 10 # 10 means that email will be sent only once per each unique token
    request_token_suffix: _airdrop_march_referrals # Email with same token will be sent only once

    template_name: airdrop_referral.html

    template_link_url: https://invest.swarm.fund

  black_list: [
"G_SOME_VALID_ACCOUNT_ADDRESS_1",
"G_SOME_VALID_ACCOUNT_ADDRESS_2"]

airdrop_march_20_20:
  issuance_asset: SWM
  snapshot_time: "2018-04-29T14:00:00" # +14 - the latest existing GMT

  source: G_SOME_VALID_PUBLIC_KEY
  signer: S_SOME_VALID_PRIVATE_KEY

  emails:
    subject: "March Madness 20/20 Airdrop"

    request_type: 10 # 10 means that email will be sent only once per each unique token
    request_token_suffix: _airdrop_march_20_20 # Email with same token will be sent only once

    template_name: airdop_20-20.html

    template_link_url: https://invest.swarm.fund

  black_list: [
"G_SOME_VALID_ACCOUNT_ADDRESS_1",
"G_SOME_VALID_ACCOUNT_ADDRESS_2"]

# kyc
identity_mind:
  connector:
    url: https://sandbox.identitymind.com/im
    auth_key: ID_MIND_AUTH_KEY # base64(user:password)
  reject_reasons:
    kyc_state_rejected: "KYC service rejected" # Make sure the string is shorter than 256
    fraud_policy_result_denied: "KYC service policy evaluation denied" # Make sure the string is shorter than 256
    invalid_kyc_data: "KYC data is invalid" # Make sure the string is shorter than 256
#    policy_evaluation_rules_fired: "Policy evaluation rules fired" # Make sure the string is shorter than 256
  emails:
    subject: "IDMind pending KYC requests waiting for manual review"
    request_type: 7 # 7 means that email with unique token will be sent only once in 24h
    message: "There are some pending KYC requests waiting for manual review in IDMind. Please, do the manual review."
    send_period: 30m # is being parsed to time.Duration (see time.ParseDuration() for possible time.Duration value formats)
  emails_to_notify: [
"john.doe@example.com",
"jane.doe@example.com"]

  source: G_SOME_VALID_PUBLIC_KEY
  signer: S_SOME_VALID_PRIVATE_KEY


template_provider:
  host: localhost
  port: 2323
  bucket: "template"
  skip_signature_check: true

wallet_cleaner:
  expire_duration: 128h

invest_ready:
  connector:
    url: https://api.sandbox.investready.com
    client_id: ourClientIDInInvestReady
    client_secret: ourClientSecretInInvestReady
    riderect_uri: https://invest.swarm.fund # The RedirectURI set in the InvestReady cabinet

  redirects:
    host: localhost
    port: 8007
    timeout: 30s

  source: G_SOME_VALID_PUBLIC_KEY
  signer: S_SOME_VALID_PRIVATE_KEY
