// Code generated by mockery v1.0.0
package snapshoter

import mock "github.com/stretchr/testify/mock"
import state "gitlab.com/swarmfund/psim/psim/taxman/internal/state"

// mockPayoutBuilder is an autogenerated mock type for the payoutBuilder type
type mockPayoutBuilder struct {
	mock.Mock
}

// BuildOperations provides a mock function with given fields: result, payoutInto, typeOfPayout
func (_m *mockPayoutBuilder) BuildOperations(result map[string]OperationSync, payoutInto map[state.AccountID]map[state.AssetCode]int64, typeOfPayout payoutType) error {
	ret := _m.Called(result, payoutInto, typeOfPayout)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]OperationSync, map[state.AccountID]map[state.AssetCode]int64, payoutType) error); ok {
		r0 = rf(result, payoutInto, typeOfPayout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
