// Code generated by mockery v1.0.0
package snapshoter

import mock "github.com/stretchr/testify/mock"
import state "gitlab.com/tokend/psim/psim/taxman/internal/state"

// mockReferralShareProvider is an autogenerated mock type for the referralShareProvider type
type mockReferralShareProvider struct {
	mock.Mock
}

// GetReferralSharePayout provides a mock function with given fields:
func (_m *mockReferralShareProvider) GetReferralSharePayout() (map[state.AccountID]map[state.AssetCode]int64, error) {
	ret := _m.Called()

	var r0 map[state.AccountID]map[state.AssetCode]int64
	if rf, ok := ret.Get(0).(func() map[state.AccountID]map[state.AssetCode]int64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[state.AccountID]map[state.AssetCode]int64)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
