// Code generated by mockery v1.0.0
package finder

import mock "github.com/stretchr/testify/mock"

// mockPriceClusterer is an autogenerated mock type for the priceClusterer type
type mockPriceClusterer struct {
	mock.Mock
}

// GetClusterForPoint provides a mock function with given fields: point
func (_m *mockPriceClusterer) GetClusterForPoint(point pricePoint) []pricePoint {
	ret := _m.Called(point)

	var r0 []pricePoint
	if rf, ok := ret.Get(0).(func(pricePoint) []pricePoint); ok {
		r0 = rf(point)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pricePoint)
		}
	}

	return r0
}
