// Code generated by mockery v1.0.0
package finder

import mock "github.com/stretchr/testify/mock"
import provider "gitlab.com/swarmfund/psim/psim/ratesync/provider"
import time "time"

// mockRatesProvider is an autogenerated mock type for the ratesProvider type
type mockRatesProvider struct {
	mock.Mock
}

// GetName provides a mock function with given fields:
func (_m *mockRatesProvider) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPoints provides a mock function with given fields:
func (_m *mockRatesProvider) GetPoints() ([]provider.PricePoint, error) {
	ret := _m.Called()

	var r0 []provider.PricePoint
	if rf, ok := ret.Get(0).(func() []provider.PricePoint); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]provider.PricePoint)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveOldPoints provides a mock function with given fields: minAllowedTime
func (_m *mockRatesProvider) RemoveOldPoints(minAllowedTime time.Time) {
	_m.Called(minAllowedTime)
}
