// Code generated by mockery v1.0.0. DO NOT EDIT.

package finder

import mock "github.com/stretchr/testify/mock"
import time "time"
import types "gitlab.com/swarmfund/psim/psim/prices/types"

// MockPriceProvider is an autogenerated mock type for the PriceProvider type
type MockPriceProvider struct {
	mock.Mock
}

// GetName provides a mock function with given fields:
func (_m *MockPriceProvider) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPoints provides a mock function with given fields:
func (_m *MockPriceProvider) GetPoints() []types.PricePoint {
	ret := _m.Called()

	var r0 []types.PricePoint
	if rf, ok := ret.Get(0).(func() []types.PricePoint); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.PricePoint)
		}
	}

	return r0
}

// RemoveOldPoints provides a mock function with given fields: minAllowedTime
func (_m *MockPriceProvider) RemoveOldPoints(minAllowedTime time.Time) {
	_m.Called(minAllowedTime)
}
