// Code generated by mockery v1.0.0. DO NOT EDIT.

package finder

import mock "github.com/stretchr/testify/mock"
import types "gitlab.com/swarmfund/psim/psim/prices/types"

// mockPriceClusterizer is an autogenerated mock type for the priceClusterizer type
type mockPriceClusterizer struct {
	mock.Mock
}

// GetClusterForPoint provides a mock function with given fields: point
func (_m *mockPriceClusterizer) GetClusterForPoint(point types.PricePoint) []providerPricePoint {
	ret := _m.Called(point)

	var r0 []providerPricePoint
	if rf, ok := ret.Get(0).(func(types.PricePoint) []providerPricePoint); ok {
		r0 = rf(point)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]providerPricePoint)
		}
	}

	return r0
}
