package mocks

import (
	"github.com/stretchr/testify/mock"
	"gitlab.com/distributed_lab/notificator-server/client"
)

// NotificatorConn is an autogenerated mock type for the NotificatorConn type
type NotificatorConnector struct {
	mock.Mock
}

// Send provides a mock function with given fields: requestType, token, payload
func (_m *NotificatorConnector) Send(requestType int, token string, payload notificator.Payload) (*notificator.Response, error) {
	ret := _m.Called(requestType, token, payload)

	var r0 *notificator.Response
	if rf, ok := ret.Get(0).(func(int, string, notificator.Payload) *notificator.Response); ok {
		r0 = rf(requestType, token, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notificator.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, string, notificator.Payload) error); ok {
		r1 = rf(requestType, token, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
