// Code generated by mockery v1.0.0
package mocks

import (
	"github.com/stretchr/testify/mock"
	"gitlab.com/tokend/horizon-connector"
)

// UserConnector is an autogenerated mock type for the UserConnector type
type UserConnector struct {
	mock.Mock
}

// User provides a mock function with given fields: accountID
func (_m *UserConnector) User(accountID string) (*horizon.User, error) {
	ret := _m.Called(accountID)

	var r0 *horizon.User
	if rf, ok := ret.Get(0).(func(string) *horizon.User); ok {
		r0 = rf(accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*horizon.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
