// Code generated by mockery v1.0.0
package mocks

import horizon "gitlab.com/swarmfund/horizon-connector"
import mock "github.com/stretchr/testify/mock"

// HorizonTxHandler is an autogenerated mock type for the HorizonTxHandler type
type HorizonTxHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: transaction
func (_m *HorizonTxHandler) Handle(transaction horizon.Transaction) error {
	ret := _m.Called(transaction)

	var r0 error
	if rf, ok := ret.Get(0).(func(horizon.Transaction) error); ok {
		r0 = rf(transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
